dist: bionic
language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
jobs:
  include:
    - python: 3.5
      dist: xenial
script:
  - pip install coveralls pytest pytest-cov
  - pytest tests.py --cov querypp
after_script:
  - coveralls
