dist: bionic
language: python
python:
  - 3.6
  - 3.7
jobs:
  include:
    - python: 3.5
      dist: xenial
script:
  - pip install coveralls isort pylint pytest pytest-cov
  - pytest tests.py --cov querypp --cov-report term-missing:skip-covered --cov-branch
  - pylint querypp
  - isort . --check-only --recursive
after_script:
  - coveralls
